name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  flutter_launcher_icons: ^0.7.4
  geolocator : ^5.1.5
  url_launcher: ^5.4.2
  location_permissions: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/flutter-icon.png
    - assets/mcan-notifier.png
    - assets/ic_launcher.png

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/mcan-notifier.png"